apiVersion: v1
kind: Service
metadata:
  name: node-exporter-service
  annotations:
    prometheus.io/port: "9100"
    prometheus.io/scrape: "true"
  namespace: monitoring
spec:
  ports:
  - name: node-exporter
    port: 9100
    protocol: TCP
    targetPort: 9100
  selector:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: node-exporter
  sessionAffinity: None
  type: ClusterIP

