apiVersion: v1
kind: Service
metadata:
  labels:
    app: webserver
    service: cog
  name: cogwebserver-azure-service
spec:
  clusterIP: None
  ports:
  - port: 8000
  selector:
    app: cog-webserver-azure
    service: cog