apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-2:461746121762:certificate/e2cc5fc3-9c44-4036-b095-579e361af081
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
  name: cogwebserver-service-lb
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8000
  - name: https
    port: 443
    targetPort: 8000
  selector:
    app: cog-webserver-dlp
    service: cog
  type: LoadBalancer