apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: 
  name: cluster-access-role-devops
rules:
  - apiGroups: ["","apps","networking.k8s.io","gateway.solo.io"]
    resources: ["events","replicasets","nodes","daemonsets","statefulsets","ingresses","namespaces","pods/log","virtualservices","routetables"]
    verbs: ["get","list","watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","list","watch","delete"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: ["","apps"]
    resources: ["events","services","configmaps","deployments"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-access-binding-devops
subjects:
  - kind: Group
    name: devops
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-access-role-devops
  apiGroup: rbac.authorization.k8s.io