apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dlp-prod-us
  region: us-east-2
  version: "1.21"

managedNodeGroups:
  - name: dlp
    minSize: 1
    maxSize: 3
    desiredCapacity: 2
    volumeSize: 20
    labels: {app: dlp}
    instanceType: t3.medium
    privateNetworking: True
  - name: azure
    minSize: 1
    maxSize: 3
    desiredCapacity: 2
    volumeSize: 20
    labels: {app: azure}
    instanceType: t3.medium
    privateNetworking: True
  - name: workflow
    minSize: 1
    maxSize: 3
    desiredCapacity: 2
    volumeSize: 20
    labels: {app: workflow}
    instanceType: t3.medium
    privateNetworking: True
  - name: cog-dlp
    minSize: 1
    maxSize: 3
    desiredCapacity: 2
    volumeSize: 20
    labels: {app: workflow}
    instanceType: t3.medium
    privateNetworking: True
  - name: cog-msgraph
    minSize: 1
    maxSize: 3
    desiredCapacity: 2
    volumeSize: 20
    labels: {app: workflow}
    instanceType: t3.medium
    privateNetworking: True
  - name: cog-workflow
    minSize: 1
    maxSize: 3
    desiredCapacity: 2
    volumeSize: 20
    labels: {app: workflow}
    instanceType: t3.medium
    privateNetworking: True
