.Overprovisioning Deployment:
  extends: .k8 deployment
  variables:
    DEPLOY_PATH: "utility/overprovisioning.yml"
  rules:
    - if: $CI_COMMIT_REF == "master"
      changes:
        - $DEPLOY_PATH
      when: manual

DEV Overprovisioning:
    stage: Cluster Utility
    extends: .Overprovisioning Deployment
    variables:
      CLUSTER: mdmtest
      ENVIRONMENT: DEV
    environment:
      name: ${ENVIRONMENT}
      action: prepare 


QA Overprovisioning:
    stage: Cluster Utility
    extends: .Overprovisioning Deployment
    variables:
      CLUSTER: mdm-qa
      ENVIRONMENT: QA 
    environment:
      name: ${ENVIRONMENT}
      action: prepare